export const dataMainCarousel = [
	{
		itemName: "Base Líquida DAZZLE",
		srcImgOne: "/img/face-cream.svg",
		srcImgTwo: "/img/ginger-woman.svg",
	},
	{
		itemName: "Base Líquida DAZZLE",
		srcImgOne: "/img/face-cream.svg",
		srcImgTwo: "/img/ginger-woman.svg",
	},
	{
		itemName: "Base Líquida DAZZLE",
		srcImgOne: "/img/face-cream.svg",
		srcImgTwo: "/img/ginger-woman.svg",
	},
];

export const dataShowcaseCarousel = [
	{
		nameItem: "Esponja 3D Dazzle",
		srcImg: "/img/sponge.svg",
		rating: 4,
		price: 36.9,
		isPromo: true,
		promoPrice: 29.9,
	},
	{
		nameItem: "Base Líquida Hyaluronic Hydra Dazzle Escuro 2 - 500g",
		srcImg: "/img/base.svg",
		rating: 4,
		price: 89.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Grace La Rose Sublime Deo Colônia Pocket 15ml",
		srcImg: "/img/colonia.svg",
		rating: 4,
		price: 39.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Pó Compacto HD Cover	Claro 2 Dazzle - 12g",
		srcImg: "/img/po-compacto.svg",
		rating: 4,
		price: 46.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Esponja 3D Dazzle",
		srcImg: "/img/sponge.svg",
		rating: 4,
		price: 36.9,
		isPromo: true,
		promoPrice: 29.9,
	},
	{
		nameItem: "Base Líquida Hyaluronic Hydra Dazzle Escuro 2 - 500g",
		srcImg: "/img/base.svg",
		rating: 4,
		price: 89.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Grace La Rose Sublime Deo Colônia Pocket 15ml",
		srcImg: "/img/colonia.svg",
		rating: 4,
		price: 39.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Pó Compacto HD Cover	Claro 2 Dazzle - 12g",
		srcImg: "/img/po-compacto.svg",
		rating: 4,
		price: 46.9,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselCreme = [
	{
		nameItem: "Corps Lígnea Body Contour Gel Modelador 500g",
		srcImg: "/img/gel-modelador.svg",
		rating: 4,
		price: 60,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Shake de Vanilla H+ HND - 550g",
		srcImg: "/img/shake-vanila.svg",
		rating: 4,
		price: 99.9,
		isPromo: true,
		promoPrice: 79.9,
	},
	{
		nameItem: "Shake de Morango H+ HND - 550g",
		srcImg: "/img/shake-morango.svg",
		rating: 4,
		price: 99.9,
		isPromo: true,
		promoPrice: 79.9,
	},
	{
		nameItem: "Luva de Silicone Creme para as Mãos Hands 100g",
		srcImg: "/img/creme-mao.svg",
		rating: 4,
		price: 25,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Corps Lígnea Body Contour Gel Modelador 500g",
		srcImg: "/img/gel-modelador.svg",
		rating: 4,
		price: 60,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Shake de Vanilla H+ HND - 550g",
		srcImg: "/img/shake-vanila.svg",
		rating: 4,
		price: 99.9,
		isPromo: true,
		promoPrice: 79.9,
	},
	{
		nameItem: "Shake de Morango H+ HND - 550g",
		srcImg: "/img/shake-morango.svg",
		rating: 4,
		price: 99.9,
		isPromo: true,
		promoPrice: 79.9,
	},
	{
		nameItem: "Luva de Silicone Creme para as Mãos Hands 100g",
		srcImg: "/img/creme-mao.svg",
		rating: 4,
		price: 25,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselHealth = [
	{
		nameItem: "Café Verde 120 cápsulas",
		srcImg: "/img/cafe-verde.svg",
		rating: 4,
		price: 69.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Ácido Hialurônico com Colágeno HND 30 Sachês de 4g",
		srcImg: "/img/colageno.svg",
		rating: 4,
		price: 175,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Slim Max HND 120 Cápsulas",
		srcImg: "/img/slim-max.svg",
		rating: 4,
		price: 140,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Chá H+ Frutas Vermelhas 150g",
		srcImg: "/img/cha-frutas-red.svg",
		rating: 4,
		price: 85,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselSkin = [
	{
		nameItem: "Corps Lígnea Wonderful Gold Óleo para as Pernas - 150ml",
		srcImg: "/img/oleo-corpo.svg",
		rating: 4,
		price: 45.0,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Corps Lígnea Body Contour Esfoliante Corporal - 200g",
		srcImg: "/img/esfoliante-corporal.svg",
		rating: 4,
		price: 49,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Gel para Massagem Feelin Hot Morango 60ml",
		srcImg: "/img/gel-massagem.svg",
		rating: 4,
		price: 27,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Óleo para as Pernas Wonderful 140ml",
		srcImg: "/img/oleo-perna.svg",
		rating: 4,
		price: 39,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Corps Lígnea Wonderful Gold Óleo para as Pernas - 150ml",
		srcImg: "/img/oleo-corpo.svg",
		rating: 4,
		price: 45.0,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Corps Lígnea Body Contour Esfoliante Corporal - 200g",
		srcImg: "/img/esfoliante-corporal.svg",
		rating: 4,
		price: 49,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Gel para Massagem Feelin Hot Morango 60ml",
		srcImg: "/img/gel-massagem.svg",
		rating: 4,
		price: 27,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Óleo para as Pernas Wonderful 140ml",
		srcImg: "/img/oleo-perna.svg",
		rating: 4,
		price: 39,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselNewProducts = [
	{
		nameItem: "Deo Colônia Venyx L’Or 100ml",
		srcImg: "/img/deo-colonia.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Desodorante Roll On Dynamic",
		srcImg: "/img/rollon-dynamic.svg",
		rating: 4,
		price: 17.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Erva Doce Sabonete Cremoso Facial Hinode 250ml",
		srcImg: "/img/sabonete=facial.svg",
		rating: 4,
		price: 33.4,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "HND Shake Triple Chocolate 450g",
		srcImg: "/img/shake-triple.svg",
		rating: 4,
		price: 109.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Deo Colônia Venyx L’Or 100ml",
		srcImg: "/img/deo-colonia.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Desodorante Roll On Dynamic",
		srcImg: "/img/rollon-dynamic.svg",
		rating: 4,
		price: 17.9,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Erva Doce Sabonete Cremoso Facial Hinode 250ml",
		srcImg: "/img/sabonete=facial.svg",
		rating: 4,
		price: 33.4,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "HND Shake Triple Chocolate 450g",
		srcImg: "/img/shake-triple.svg",
		rating: 4,
		price: 109.9,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselFragancies = [
	{
		nameItem: "Lattitude Expedition 100ml",
		srcImg: "/img/fragancia-expedition.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Empire VIP 100ml",
		srcImg: "/img/fragancia-vip.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Empire 100ml",
		srcImg: "/img/fragancia-nao-vip.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Lattitude Stamina 100ml",
		srcImg: "/img/fragancia-stamina.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Lattitude Expedition 100ml",
		srcImg: "/img/fragancia-expedition.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Empire VIP 100ml",
		srcImg: "/img/fragancia-vip.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Empire 100ml",
		srcImg: "/img/fragancia-nao-vip.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Lattitude Stamina 100ml",
		srcImg: "/img/fragancia-stamina.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
];

export const dataShowcaseCarouselNewFragancies = [
	{
		nameItem: "Empire Gold 100ml",
		srcImg: "/img/fragancia-gold.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Colônia Lattitude Origin 100ml",
		srcImg: "/img/fragancia-origin.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Colônia Ella Juicy 100ml",
		srcImg: "/img/fragancia-juicy.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Spot For Her 75ml",
		srcImg: "/img/fragancia-her.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Empire Gold 100ml",
		srcImg: "/img/fragancia-gold.svg",
		rating: 4,
		price: 150,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Colônia Lattitude Origin 100ml",
		srcImg: "/img/fragancia-origin.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Colônia Ella Juicy 100ml",
		srcImg: "/img/fragancia-juicy.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
	{
		nameItem: "Spot For Her 75ml",
		srcImg: "/img/fragancia-her.svg",
		rating: 4,
		price: 129,
		isPromo: false,
		promoPrice: 0,
	},
];
